var WasmVideoEncoderTest2 = function(WasmVideoEncoderTest2) {
  WasmVideoEncoderTest2 = WasmVideoEncoderTest2 || {};

var c;c||(c=typeof WasmVideoEncoderTest2 !== 'undefined' ? WasmVideoEncoderTest2 : {});var f={},l;for(l in c)c.hasOwnProperty(l)&&(f[l]=c[l]);c.arguments=[];c.thisProgram="./this.program";c.quit=function(a,b){throw b;};c.preRun=[];c.postRun=[];var m=!1,n=!1,q=!1,r=!1;
if(c.ENVIRONMENT)if("WEB"===c.ENVIRONMENT)m=!0;else if("WORKER"===c.ENVIRONMENT)n=!0;else if("NODE"===c.ENVIRONMENT)q=!0;else if("SHELL"===c.ENVIRONMENT)r=!0;else throw Error("Module['ENVIRONMENT'] value is not valid. must be one of: WEB|WORKER|NODE|SHELL.");else m="object"===typeof window,n="function"===typeof importScripts,q="object"===typeof process&&"function"===typeof require&&!m&&!n,r=!m&&!q&&!n;
if(q){var aa,ba;c.read=function(a,b){aa||(aa=require("fs"));ba||(ba=require("path"));a=ba.normalize(a);a=aa.readFileSync(a);return b?a:a.toString()};c.readBinary=function(a){a=c.read(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a};1<process.argv.length&&(c.thisProgram=process.argv[1].replace(/\\/g,"/"));c.arguments=process.argv.slice(2);process.on("uncaughtException",function(a){if(!(a instanceof t))throw a;});process.on("unhandledRejection",function(){process.exit(1)});c.inspect=
function(){return"[Emscripten Module object]"}}else if(r)"undefined"!=typeof read&&(c.read=function(a){return read(a)}),c.readBinary=function(a){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(a));a=read(a,"binary");assert("object"===typeof a);return a},"undefined"!=typeof scriptArgs?c.arguments=scriptArgs:"undefined"!=typeof arguments&&(c.arguments=arguments),"function"===typeof quit&&(c.quit=function(a){quit(a)});else if(m||n)c.read=function(a){var b=new XMLHttpRequest;b.open("GET",
a,!1);b.send(null);return b.responseText},n&&(c.readBinary=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),c.readAsync=function(a,b,e){var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=function(){200==d.status||0==d.status&&d.response?b(d.response):e()};d.onerror=e;d.send(null)},"undefined"!=typeof arguments&&(c.arguments=arguments),c.setWindowTitle=function(a){document.title=a};
c.print="undefined"!==typeof console?console.log.bind(console):"undefined"!==typeof print?print:null;c.printErr="undefined"!==typeof printErr?printErr:"undefined"!==typeof console&&console.warn.bind(console)||c.print;c.print=c.print;c.printErr=c.printErr;for(l in f)f.hasOwnProperty(l)&&(c[l]=f[l]);f=void 0;function u(a){assert(!ca);var b=v;v=v+a+15&-16;return b}function da(a){assert(w);var b=x[w>>2];a=b+a+15&-16;x[w>>2]=a;return a>=y&&!ea()?(x[w>>2]=b,0):b}
function fa(a){var b;b||(b=16);return Math.ceil(a/b)*b}var ha=0;function assert(a,b){a||z("Assertion failed: "+b)}function A(a,b){if("number"===typeof a){var e=!0;var d=a}else e=!1,d=a.length;b=4==b?g:["function"===typeof ia?ia:u,ja,u,da][void 0===b?2:b](Math.max(d,1));if(e){var g=b;assert(0==(b&3));for(a=b+(d&-4);g<a;g+=4)x[g>>2]=0;for(a=b+d;g<a;)B[g++>>0]=0;return b}a.subarray||a.slice?C.set(a,b):C.set(new Uint8Array(a),b);return b}
function E(a){var b;if(0===b||!a)return"";for(var e=0,d,g=0;;){d=C[a+g>>0];e|=d;if(0==d&&!b)break;g++;if(b&&g==b)break}b||(b=g);d="";if(128>e){for(;0<b;)e=String.fromCharCode.apply(String,C.subarray(a,a+Math.min(b,1024))),d=d?d+e:e,a+=1024,b-=1024;return d}return ka(C,a)}var la="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function ka(a,b){for(var e=b;a[e];)++e;if(16<e-b&&a.subarray&&la)return la.decode(a.subarray(b,e));for(e="";;){var d=a[b++];if(!d)return e;if(d&128){var g=a[b++]&63;if(192==(d&224))e+=String.fromCharCode((d&31)<<6|g);else{var h=a[b++]&63;if(224==(d&240))d=(d&15)<<12|g<<6|h;else{var k=a[b++]&63;if(240==(d&248))d=(d&7)<<18|g<<12|h<<6|k;else{var p=a[b++]&63;if(248==(d&252))d=(d&3)<<24|g<<18|h<<12|k<<6|p;else{var D=a[b++]&63;d=(d&1)<<30|g<<24|h<<18|k<<12|p<<6|D}}}65536>d?e+=String.fromCharCode(d):(d-=
65536,e+=String.fromCharCode(55296|d>>10,56320|d&1023))}}else e+=String.fromCharCode(d)}}
function ma(a,b,e,d){if(0<d){d=e+d-1;for(var g=0;g<a.length;++g){var h=a.charCodeAt(g);55296<=h&&57343>=h&&(h=65536+((h&1023)<<10)|a.charCodeAt(++g)&1023);if(127>=h){if(e>=d)break;b[e++]=h}else{if(2047>=h){if(e+1>=d)break;b[e++]=192|h>>6}else{if(65535>=h){if(e+2>=d)break;b[e++]=224|h>>12}else{if(2097151>=h){if(e+3>=d)break;b[e++]=240|h>>18}else{if(67108863>=h){if(e+4>=d)break;b[e++]=248|h>>24}else{if(e+5>=d)break;b[e++]=252|h>>30;b[e++]=128|h>>24&63}b[e++]=128|h>>18&63}b[e++]=128|h>>12&63}b[e++]=
128|h>>6&63}b[e++]=128|h&63}}b[e]=0}}function na(a){for(var b=0,e=0;e<a.length;++e){var d=a.charCodeAt(e);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++e)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:2097151>=d?b+4:67108863>=d?b+5:b+6}return b}"undefined"!==typeof TextDecoder&&new TextDecoder("utf-16le");var oa=65536,pa=16777216,qa=16777216;function ra(a,b){0<a%b&&(a+=b-a%b);return a}var buffer,B,C,sa,x;
function ta(){c.HEAP8=B=new Int8Array(buffer);c.HEAP16=sa=new Int16Array(buffer);c.HEAP32=x=new Int32Array(buffer);c.HEAPU8=C=new Uint8Array(buffer);c.HEAPU16=new Uint16Array(buffer);c.HEAPU32=new Uint32Array(buffer);c.HEAPF32=new Float32Array(buffer);c.HEAPF64=new Float64Array(buffer)}var F,v,ca,ua,G,va,wa,w;F=v=ua=G=va=wa=w=0;ca=!1;
c.reallocBuffer||(c.reallocBuffer=function(a){try{if(ArrayBuffer.o)var b=ArrayBuffer.o(buffer,a);else{var e=B;b=new ArrayBuffer(a);(new Int8Array(b)).set(e)}}catch(d){return!1}return xa(b)?b:!1});function ea(){var a=c.usingWasm?oa:pa,b=2147483648-a;if(x[w>>2]>b)return!1;var e=y;for(y=Math.max(y,qa);y<x[w>>2];)536870912>=y?y=ra(2*y,a):y=Math.min(ra((3*y+2147483648)/4,a),b);a=c.reallocBuffer(y);if(!a||a.byteLength!=y)return y=e,!1;c.buffer=buffer=a;ta();return!0}var ya;
try{ya=Function.prototype.call.bind(Object.getOwnPropertyDescriptor(ArrayBuffer.prototype,"byteLength").get),ya(new ArrayBuffer(4))}catch(a){ya=function(b){return b.byteLength}}var za=c.TOTAL_STACK||5242880,y=c.TOTAL_MEMORY||16777216;y<za&&c.printErr("TOTAL_MEMORY should be larger than TOTAL_STACK, was "+y+"! (TOTAL_STACK="+za+")");
c.buffer?buffer=c.buffer:("object"===typeof WebAssembly&&"function"===typeof WebAssembly.Memory?(c.wasmMemory=new WebAssembly.Memory({initial:y/oa}),buffer=c.wasmMemory.buffer):buffer=new ArrayBuffer(y),c.buffer=buffer);ta();x[0]=1668509029;sa[1]=25459;if(115!==C[2]||99!==C[3])throw"Runtime error: expected the system to be little-endian!";
function H(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b();else{var e=b.u;"number"===typeof e?void 0===b.g?c.dynCall_v(e):c.dynCall_vi(e,b.g):e(void 0===b.g?null:b.g)}}}var Aa=[],Ba=[],Ca=[],Da=[],Ea=[],Fa=!1;function Ga(){var a=c.preRun.shift();Aa.unshift(a)}var Ha=Math.abs,Ia=Math.trunc,I=0,Ja=null,J=null;c.preloadedImages={};c.preloadedAudios={};
function K(a){return String.prototype.startsWith?a.startsWith("data:application/octet-stream;base64,"):0===a.indexOf("data:application/octet-stream;base64,")}
(function(){function a(){try{if(c.wasmBinary)return new Uint8Array(c.wasmBinary);if(c.readBinary)return c.readBinary(g);throw"on the web, we need the wasm binary to be preloaded and set on Module['wasmBinary']. emcc.py will do that for you when generating HTML (but not JS)";}catch(Xa){z(Xa)}}function b(){return c.wasmBinary||!m&&!n||"function"!==typeof fetch?new Promise(function(b){b(a())}):fetch(g,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+
g+"'";return a.arrayBuffer()}).catch(function(){return a()})}function e(a){function e(a){p=a.exports;if(p.memory){a=p.memory;var b=c.buffer;a.byteLength<b.byteLength&&c.printErr("the new buffer in mergeMemory is smaller than the previous one. in native wasm, we should grow memory here");b=new Int8Array(b);(new Int8Array(a)).set(b);c.buffer=buffer=a;ta()}c.asm=p;c.usingWasm=!0;I--;c.monitorRunDependencies&&c.monitorRunDependencies(I);0==I&&(null!==Ja&&(clearInterval(Ja),Ja=null),J&&(a=J,J=null,a()))}
function d(a){e(a.instance)}function h(a){b().then(function(a){return WebAssembly.instantiate(a,k)}).then(a).catch(function(a){c.printErr("failed to asynchronously prepare wasm: "+a);z(a)})}if("object"!==typeof WebAssembly)return c.printErr("no native wasm support detected"),!1;if(!(c.wasmMemory instanceof WebAssembly.Memory))return c.printErr("no native wasm Memory in use"),!1;a.memory=c.wasmMemory;k.global={NaN:NaN,Infinity:Infinity};k["global.Math"]=Math;k.env=a;I++;c.monitorRunDependencies&&c.monitorRunDependencies(I);
if(c.instantiateWasm)try{return c.instantiateWasm(k,e)}catch(Ya){return c.printErr("Module.instantiateWasm callback failed with error: "+Ya),!1}c.wasmBinary||"function"!==typeof WebAssembly.instantiateStreaming||K(g)||"function"!==typeof fetch?h(d):WebAssembly.instantiateStreaming(fetch(g,{credentials:"same-origin"}),k).then(d).catch(function(a){c.printErr("wasm streaming compile failed: "+a);c.printErr("falling back to ArrayBuffer instantiation");h(d)});return{}}var d="WasmVideoEncoderTest2.wast",
g="WasmVideoEncoderTest2.wasm",h="WasmVideoEncoderTest2.temp.asm.js";"function"===typeof c.locateFile&&(K(d)||(d=c.locateFile(d)),K(g)||(g=c.locateFile(g)),K(h)||(h=c.locateFile(h)));var k={global:null,env:null,asm2wasm:{"f64-rem":function(a,b){return a%b},"debugger":function(){debugger}},parent:c},p=null;c.asmPreload=c.asm;var D=c.reallocBuffer;c.reallocBuffer=function(a){if("asmjs"===Za)var b=D(a);else a:{a=ra(a,c.usingWasm?oa:pa);var d=c.buffer.byteLength;if(c.usingWasm)try{b=-1!==c.wasmMemory.grow((a-
d)/65536)?c.buffer=c.wasmMemory.buffer:null;break a}catch(eb){b=null;break a}b=void 0}return b};var Za="";c.asm=function(a,b){if(!b.table){a=c.wasmTableSize;void 0===a&&(a=1024);var d=c.wasmMaxTableSize;b.table="object"===typeof WebAssembly&&"function"===typeof WebAssembly.Table?void 0!==d?new WebAssembly.Table({initial:a,maximum:d,element:"anyfunc"}):new WebAssembly.Table({initial:a,element:"anyfunc"}):Array(a);c.wasmTable=b.table}b.memoryBase||(b.memoryBase=c.STATIC_BASE);b.tableBase||(b.tableBase=
0);(b=e(b))||z("no binaryen method succeeded. consider enabling more options, like interpreting, if you want that: https://github.com/kripken/emscripten/wiki/WebAssembly#binaryen-methods");return b}})();F=1024;v=F+1320784;Ba.push();c.STATIC_BASE=F;c.STATIC_BUMP=1320784;v+=16;var L=0;function M(){L+=4;return x[L-4>>2]}var N={};
function O(a,b){L=b;try{var e=M(),d=M(),g=M();a=0;O.c||(O.c=[null,[],[]],O.j=function(a,b){var d=O.c[a];assert(d);0===b||10===b?((1===a?c.print:c.printErr)(ka(d,0)),d.length=0):d.push(b)});for(b=0;b<g;b++){for(var h=x[d+8*b>>2],k=x[d+(8*b+4)>>2],p=0;p<k;p++)O.j(e,C[h+p]);a+=k}return a}catch(D){return"undefined"!==typeof FS&&D instanceof FS.a||z(D),-D.b}}function Ka(a){c.___errno_location&&(x[c.___errno_location()>>2]=a);return a}
function P(){void 0===P.start&&(P.start=Date.now());return 1E3*(Date.now()-P.start)|0}function Q(){z()}var La=v;v+=16;var Ma,R={};function S(a){if(0===a)return 0;a=E(a);if(!R.hasOwnProperty(a))return 0;S.c&&Na(S.c);a=R[a];var b=na(a)+1,e=ia(b);e&&ma(a,B,e,b);S.c=e;return S.c}var Pa=A(Oa("GMT"),2);
A([8,0,1,0,2,0,1,0,3,0,1,0,2,0,1,0,4,0,1,0,2,0,1,0,3,0,1,0,2,0,1,0,5,0,1,0,2,0,1,0,3,0,1,0,2,0,1,0,4,0,1,0,2,0,1,0,3,0,1,0,2,0,1,0,6,0,1,0,2,0,1,0,3,0,1,0,2,0,1,0,4,0,1,0,2,0,1,0,3,0,1,0,2,0,1,0,5,0,1,0,2,0,1,0,3,0,1,0,2,0,1,0,4,0,1,0,2,0,1,0,3,0,1,0,2,0,1,0,7,0,1,0,2,0,1,0,3,0,1,0,2,0,1,0,4,0,1,0,2,0,1,0,3,0,1,0,2,0,1,0,5,0,1,0,2,0,1,0,3,0,1,0,2,0,1,0,4,0,1,0,2,0,1,0,3,0,1,0,2,0,1,0,6,0,1,0,2,0,1,0,3,0,1,0,2,0,1,0,4,0,1,0,2,0,1,0,3,0,1,0,2,0,1,0,5,0,1,0,2,0,1,0,3,0,1,0,2,0,1,0,4,0,1,0,2,0,1,0,3,
0,1,0,2,0,1,0],2);function Qa(a){return Math.pow(2,a)}var T=v,Ra=v+=16,Sa=v+=16;v+=16;function Ta(){function a(a){return(a=a.toTimeString().match(/\(([A-Za-z ]+)\)$/))?a[1]:"GMT"}if(!Ua){Ua=!0;x[Sa>>2]=60*(new Date).getTimezoneOffset();var b=new Date(2E3,0,1),e=new Date(2E3,6,1);x[Ra>>2]=Number(b.getTimezoneOffset()!=e.getTimezoneOffset());var d=a(b),g=a(e);d=A(Oa(d),0);g=A(Oa(g),0);e.getTimezoneOffset()<b.getTimezoneOffset()?(x[T>>2]=d,x[T+4>>2]=g):(x[T>>2]=g,x[T+4>>2]=d)}}var Ua;
q?Q=function(){var a=process.hrtime();return 1E3*a[0]+a[1]/1E6}:"undefined"!==typeof dateNow?Q=dateNow:"object"===typeof self&&self.performance&&"function"===typeof self.performance.now?Q=function(){return self.performance.now()}:"object"===typeof performance&&"function"===typeof performance.now?Q=function(){return performance.now()}:Q=Date.now;var U,V;
Ma?(V=x[La>>2],U=x[V>>2]):(Ma=!0,R.USER=R.LOGNAME="web_user",R.PATH="/",R.PWD="/",R.HOME="/home/web_user",R.LANG="C.UTF-8",R._=c.thisProgram,U=u(1024),V=u(256),x[V>>2]=U,x[La>>2]=V);var W=[],Va=0,X;for(X in R)if("string"===typeof R[X]){var Y=X+"="+R[X];W.push(Y);Va+=Y.length}if(1024<Va)throw Error("Environment size exceeded TOTAL_ENV_SIZE!");for(var Z=0;Z<W.length;Z++){for(var Wa=Y=W[Z],$a=U,ab=0;ab<Wa.length;++ab)B[$a++>>0]=Wa.charCodeAt(ab);B[$a>>0]=0;x[V+4*Z>>2]=U;U+=Y.length+1}
x[V+4*W.length>>2]=0;w=u(4);ua=G=fa(v);va=ua+za;wa=fa(va);x[w>>2]=wa;ca=!0;function Oa(a){var b=Array(na(a)+1);ma(a,b,0,b.length);return b}c.wasmTableSize=1006;c.wasmMaxTableSize=1006;c.h={};
c.i={abort:z,enlargeMemory:ea,getTotalMemory:function(){return y},abortOnCannotGrowMemory:function(){z("Cannot enlarge memory arrays. Either (1) compile with  -s TOTAL_MEMORY=X  with X higher than the current value "+y+", (2) compile with  -s ALLOW_MEMORY_GROWTH=1  which allows increasing the size at runtime, or (3) if you want malloc to return NULL (0) instead of this abort, compile with  -s ABORTING_MALLOC=0 ")},___assert_fail:function(a,b,e,d){z("Assertion failed: "+E(a)+", at: "+[b?E(b):"unknown filename",
e,d?E(d):"unknown function"])},___lock:function(){},___setErrNo:Ka,___syscall140:function(a,b){L=b;try{var e=N.f();M();var d=M(),g=M(),h=M();FS.v(e,d,h);x[g>>2]=e.position;e.m&&0===d&&0===h&&(e.m=null);return 0}catch(k){return"undefined"!==typeof FS&&k instanceof FS.a||z(k),-k.b}},___syscall145:function(a,b){L=b;try{var e=N.f(),d=M(),g=M();return N.s(e,d,g)}catch(h){return"undefined"!==typeof FS&&h instanceof FS.a||z(h),-h.b}},___syscall146:O,___syscall195:function(a,b){L=b;try{var e=E(M()),d=M();
return N.l(FS.stat,e,d)}catch(g){return"undefined"!==typeof FS&&g instanceof FS.a||z(g),-g.b}},___syscall197:function(a,b){L=b;try{var e=N.f(),d=M();return N.l(FS.stat,e.path,d)}catch(g){return"undefined"!==typeof FS&&g instanceof FS.a||z(g),-g.b}},___syscall219:function(a,b){L=b;return 0},___syscall221:function(a,b){L=b;return 0},___syscall3:function(a,b){L=b;try{var e=N.f(),d=M(),g=M();return FS.read(e,B,d,g)}catch(h){return"undefined"!==typeof FS&&h instanceof FS.a||z(h),-h.b}},___syscall38:function(a,
b){L=b;try{var e=E(M()),d=E(M());FS.rename(e,d);return 0}catch(g){return"undefined"!==typeof FS&&g instanceof FS.a||z(g),-g.b}},___syscall5:function(a,b){L=b;try{var e=E(M()),d=M(),g=M();return FS.open(e,d,g).fd}catch(h){return"undefined"!==typeof FS&&h instanceof FS.a||z(h),-h.b}},___syscall54:function(a,b){L=b;return 0},___syscall6:function(a,b){L=b;try{var e=N.f();FS.close(e);return 0}catch(d){return"undefined"!==typeof FS&&d instanceof FS.a||z(d),-d.b}},___unlock:function(){},_abort:function(){c.abort()},
_clock:P,_clock_gettime:function(a,b){if(0===a)a=Date.now();else if(1===a&&(q||"undefined"!==typeof dateNow||(m||n)&&self.performance&&self.performance.now))a=Q();else return Ka(22),-1;x[b>>2]=a/1E3|0;x[b+4>>2]=a%1E3*1E6|0;return 0},_emscripten_memcpy_big:function(a,b,e){C.set(C.subarray(b,b+e),a);return a},_exit:function(a){c.exit(a)},_fabs:Ha,_getenv:S,_gettimeofday:function(a){var b=Date.now();x[a>>2]=b/1E3|0;x[a+4>>2]=b%1E3*1E3|0;return 0},_gmtime_r:function(a,b){a=new Date(1E3*x[a>>2]);x[b>>
2]=a.getUTCSeconds();x[b+4>>2]=a.getUTCMinutes();x[b+8>>2]=a.getUTCHours();x[b+12>>2]=a.getUTCDate();x[b+16>>2]=a.getUTCMonth();x[b+20>>2]=a.getUTCFullYear()-1900;x[b+24>>2]=a.getUTCDay();x[b+36>>2]=0;x[b+32>>2]=0;x[b+28>>2]=(a.getTime()-Date.UTC(a.getUTCFullYear(),0,1,0,0,0,0))/864E5|0;x[b+40>>2]=Pa;return b},_llvm_exp2_f32:Qa,_llvm_exp2_f64:function(){return Qa.apply(null,arguments)},_llvm_trunc_f64:Ia,_localtime_r:function(a,b){Ta();a=new Date(1E3*x[a>>2]);x[b>>2]=a.getSeconds();x[b+4>>2]=a.getMinutes();
x[b+8>>2]=a.getHours();x[b+12>>2]=a.getDate();x[b+16>>2]=a.getMonth();x[b+20>>2]=a.getFullYear()-1900;x[b+24>>2]=a.getDay();var e=new Date(a.getFullYear(),0,1);x[b+28>>2]=(a.getTime()-e.getTime())/864E5|0;x[b+36>>2]=-(60*a.getTimezoneOffset());var d=(new Date(2E3,6,1)).getTimezoneOffset();e=e.getTimezoneOffset();a=(d!=e&&a.getTimezoneOffset()==Math.min(e,d))|0;x[b+32>>2]=a;x[b+40>>2]=x[T+(a?4:0)>>2];return b},_mktime:function(a){Ta();var b=new Date(x[a+20>>2]+1900,x[a+16>>2],x[a+12>>2],x[a+8>>2],
x[a+4>>2],x[a>>2],0),e=x[a+32>>2],d=b.getTimezoneOffset(),g=new Date(b.getFullYear(),0,1),h=(new Date(2E3,6,1)).getTimezoneOffset(),k=g.getTimezoneOffset(),p=Math.min(k,h);0>e?x[a+32>>2]=Number(h!=k&&p==d):0<e!=(p==d)&&(h=Math.max(k,h),b.setTime(b.getTime()+6E4*((0<e?p:h)-d)));x[a+24>>2]=b.getDay();x[a+28>>2]=(b.getTime()-g.getTime())/864E5|0;return b.getTime()/1E3|0},_nanosleep:function(a,b){var e=x[a>>2];a=x[a+4>>2];0!==b&&(x[b>>2]=0,x[b+4>>2]=0);b=(1E6*e+a/1E3)/1E3;if((m||n)&&self.performance&&
self.performance.now)for(e=self.performance.now();self.performance.now()-e<b;);else for(e=Date.now();Date.now()-e<b;);return 0},DYNAMICTOP_PTR:w,STACKTOP:G};var bb=c.asm(c.h,c.i,buffer);c.asm=bb;c._add_frame=function(){return c.asm._add_frame.apply(null,arguments)};c._close_stream=function(){return c.asm._close_stream.apply(null,arguments)};
var xa=c._emscripten_replace_memory=function(){return c.asm._emscripten_replace_memory.apply(null,arguments)},Na=c._free=function(){return c.asm._free.apply(null,arguments)};c._free_buffer=function(){return c.asm._free_buffer.apply(null,arguments)};c._get_buffer=function(){return c.asm._get_buffer.apply(null,arguments)};var ia=c._malloc=function(){return c.asm._malloc.apply(null,arguments)};c._open_audio=function(){return c.asm._open_audio.apply(null,arguments)};
c._open_video=function(){return c.asm._open_video.apply(null,arguments)};c._write_audio_frame=function(){return c.asm._write_audio_frame.apply(null,arguments)};c._write_header=function(){return c.asm._write_header.apply(null,arguments)};var ja=c.stackAlloc=function(){return c.asm.stackAlloc.apply(null,arguments)};c.dynCall_vi=function(){return c.asm.dynCall_vi.apply(null,arguments)};c.asm=bb;
c.then=function(a){if(c.calledRun)a(c);else{var b=c.onRuntimeInitialized;c.onRuntimeInitialized=function(){b&&b();a(c)}}return c};function t(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}t.prototype=Error();t.prototype.constructor=t;J=function cb(){c.calledRun||db();c.calledRun||(J=cb)};
function db(){function a(){if(!c.calledRun&&(c.calledRun=!0,!ha)){Fa||(Fa=!0,H(Ba));H(Ca);if(c.onRuntimeInitialized)c.onRuntimeInitialized();if(c.postRun)for("function"==typeof c.postRun&&(c.postRun=[c.postRun]);c.postRun.length;){var a=c.postRun.shift();Ea.unshift(a)}H(Ea)}}if(!(0<I)){if(c.preRun)for("function"==typeof c.preRun&&(c.preRun=[c.preRun]);c.preRun.length;)Ga();H(Aa);0<I||c.calledRun||(c.setStatus?(c.setStatus("Running..."),setTimeout(function(){setTimeout(function(){c.setStatus("")},
1);a()},1)):a())}}c.run=db;c.exit=function(a,b){if(!b||!c.noExitRuntime||0!==a){if(!c.noExitRuntime&&(ha=!0,G=void 0,H(Da),c.onExit))c.onExit(a);q&&process.exit(a);c.quit(a,new t(a))}};function z(a){if(c.onAbort)c.onAbort(a);void 0!==a?(c.print(a),c.printErr(a),a=JSON.stringify(a)):a="";ha=!0;throw"abort("+a+"). Build with -s ASSERTIONS=1 for more info.";}c.abort=z;if(c.preInit)for("function"==typeof c.preInit&&(c.preInit=[c.preInit]);0<c.preInit.length;)c.preInit.pop()();c.noExitRuntime=!0;db();


  return WasmVideoEncoderTest2;
};
if (typeof exports === 'object' && typeof module === 'object')
  module.exports = WasmVideoEncoderTest2;
else if (typeof define === 'function' && define['amd'])
  define([], function() { return WasmVideoEncoderTest2; });
else if (typeof exports === 'object')
  exports["WasmVideoEncoderTest2"] = WasmVideoEncoderTest2;
