var WasmEncoder1 = function(WasmEncoder1) {
  WasmEncoder1 = WasmEncoder1 || {};

var c;c||(c=typeof WasmEncoder1 !== 'undefined' ? WasmEncoder1 : {});var f={},m;for(m in c)c.hasOwnProperty(m)&&(f[m]=c[m]);c.arguments=[];c.thisProgram="./this.program";c.quit=function(a,b){throw b;};c.preRun=[];c.postRun=[];var n=!1,q=!1,r=!1,aa=!1;
if(c.ENVIRONMENT)if("WEB"===c.ENVIRONMENT)n=!0;else if("WORKER"===c.ENVIRONMENT)q=!0;else if("NODE"===c.ENVIRONMENT)r=!0;else if("SHELL"===c.ENVIRONMENT)aa=!0;else throw Error("Module['ENVIRONMENT'] value is not valid. must be one of: WEB|WORKER|NODE|SHELL.");else n="object"===typeof window,q="function"===typeof importScripts,r="object"===typeof process&&"function"===typeof require&&!n&&!q,aa=!n&&!r&&!q;
if(r){var ba,ca;c.read=function(a,b){ba||(ba=require("fs"));ca||(ca=require("path"));a=ca.normalize(a);a=ba.readFileSync(a);return b?a:a.toString()};c.readBinary=function(a){a=c.read(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a};1<process.argv.length&&(c.thisProgram=process.argv[1].replace(/\\/g,"/"));c.arguments=process.argv.slice(2);process.on("uncaughtException",function(a){if(!(a instanceof v))throw a;});process.on("unhandledRejection",function(){process.exit(1)});c.inspect=
function(){return"[Emscripten Module object]"}}else if(aa)"undefined"!=typeof read&&(c.read=function(a){return read(a)}),c.readBinary=function(a){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(a));a=read(a,"binary");assert("object"===typeof a);return a},"undefined"!=typeof scriptArgs?c.arguments=scriptArgs:"undefined"!=typeof arguments&&(c.arguments=arguments),"function"===typeof quit&&(c.quit=function(a){quit(a)});else if(n||q)c.read=function(a){var b=new XMLHttpRequest;b.open("GET",
a,!1);b.send(null);return b.responseText},q&&(c.readBinary=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),c.readAsync=function(a,b,d){var e=new XMLHttpRequest;e.open("GET",a,!0);e.responseType="arraybuffer";e.onload=function(){200==e.status||0==e.status&&e.response?b(e.response):d()};e.onerror=d;e.send(null)},"undefined"!=typeof arguments&&(c.arguments=arguments),c.setWindowTitle=function(a){document.title=a};
c.print="undefined"!==typeof console?console.log.bind(console):"undefined"!==typeof print?print:null;c.printErr="undefined"!==typeof printErr?printErr:"undefined"!==typeof console&&console.warn.bind(console)||c.print;c.print=c.print;c.printErr=c.printErr;for(m in f)f.hasOwnProperty(m)&&(c[m]=f[m]);f=void 0;function w(a){assert(!da);var b=x;x=x+a+15&-16;return b}function ea(a){assert(y);var b=z[y>>2];a=b+a+15&-16;z[y>>2]=a;if(a=a>=A)fa(),a=!0;return a?(z[y>>2]=b,0):b}
function ha(a){var b;b||(b=16);return Math.ceil(a/b)*b}var ia=0;function assert(a,b){a||B("Assertion failed: "+b)}function C(a,b){if("number"===typeof a){var d=!0;var e=a}else d=!1,e=a.length;b=4==b?g:["function"===typeof ja?ja:w,ka,w,ea][void 0===b?2:b](Math.max(e,1));if(d){var g=b;assert(0==(b&3));for(a=b+(e&-4);g<a;g+=4)z[g>>2]=0;for(a=b+e;g<a;)D[g++>>0]=0;return b}a.subarray||a.slice?E.set(a,b):E.set(new Uint8Array(a),b);return b}
function F(a){var b;if(0===b||!a)return"";for(var d=0,e,g=0;;){e=E[a+g>>0];d|=e;if(0==e&&!b)break;g++;if(b&&g==b)break}b||(b=g);e="";if(128>d){for(;0<b;)d=String.fromCharCode.apply(String,E.subarray(a,a+Math.min(b,1024))),e=e?e+d:d,a+=1024,b-=1024;return e}return la(E,a)}var ma="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function la(a,b){for(var d=b;a[d];)++d;if(16<d-b&&a.subarray&&ma)return ma.decode(a.subarray(b,d));for(d="";;){var e=a[b++];if(!e)return d;if(e&128){var g=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|g);else{var k=a[b++]&63;if(224==(e&240))e=(e&15)<<12|g<<6|k;else{var h=a[b++]&63;if(240==(e&248))e=(e&7)<<18|g<<12|k<<6|h;else{var l=a[b++]&63;if(248==(e&252))e=(e&3)<<24|g<<18|k<<12|h<<6|l;else{var t=a[b++]&63;e=(e&1)<<30|g<<24|k<<18|h<<12|l<<6|t}}}65536>e?d+=String.fromCharCode(e):(e-=
65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}}
function na(a,b,d,e){if(!(0<e))return 0;var g=d;e=d+e-1;for(var k=0;k<a.length;++k){var h=a.charCodeAt(k);55296<=h&&57343>=h&&(h=65536+((h&1023)<<10)|a.charCodeAt(++k)&1023);if(127>=h){if(d>=e)break;b[d++]=h}else{if(2047>=h){if(d+1>=e)break;b[d++]=192|h>>6}else{if(65535>=h){if(d+2>=e)break;b[d++]=224|h>>12}else{if(2097151>=h){if(d+3>=e)break;b[d++]=240|h>>18}else{if(67108863>=h){if(d+4>=e)break;b[d++]=248|h>>24}else{if(d+5>=e)break;b[d++]=252|h>>30;b[d++]=128|h>>24&63}b[d++]=128|h>>18&63}b[d++]=128|
h>>12&63}b[d++]=128|h>>6&63}b[d++]=128|h&63}}b[d]=0;return d-g}function oa(a){for(var b=0,d=0;d<a.length;++d){var e=a.charCodeAt(d);55296<=e&&57343>=e&&(e=65536+((e&1023)<<10)|a.charCodeAt(++d)&1023);127>=e?++b:b=2047>=e?b+2:65535>=e?b+3:2097151>=e?b+4:67108863>=e?b+5:b+6}return b}"undefined"!==typeof TextDecoder&&new TextDecoder("utf-16le");var buffer,D,E,pa,z;
function qa(){c.HEAP8=D=new Int8Array(buffer);c.HEAP16=pa=new Int16Array(buffer);c.HEAP32=z=new Int32Array(buffer);c.HEAPU8=E=new Uint8Array(buffer);c.HEAPU16=new Uint16Array(buffer);c.HEAPU32=new Uint32Array(buffer);c.HEAPF32=new Float32Array(buffer);c.HEAPF64=new Float64Array(buffer)}var G,x,da,ra,H,sa,ta,y;G=x=ra=H=sa=ta=y=0;da=!1;
function fa(){B("Cannot enlarge memory arrays. Either (1) compile with  -s TOTAL_MEMORY=X  with X higher than the current value "+A+", (2) compile with  -s ALLOW_MEMORY_GROWTH=1  which allows increasing the size at runtime, or (3) if you want malloc to return NULL (0) instead of this abort, compile with  -s ABORTING_MALLOC=0 ")}var va=c.TOTAL_STACK||5242880,A=c.TOTAL_MEMORY||1073741824;A<va&&c.printErr("TOTAL_MEMORY should be larger than TOTAL_STACK, was "+A+"! (TOTAL_STACK="+va+")");
c.buffer?buffer=c.buffer:("object"===typeof WebAssembly&&"function"===typeof WebAssembly.Memory?(c.wasmMemory=new WebAssembly.Memory({initial:A/65536,maximum:A/65536}),buffer=c.wasmMemory.buffer):buffer=new ArrayBuffer(A),c.buffer=buffer);qa();z[0]=1668509029;pa[1]=25459;if(115!==E[2]||99!==E[3])throw"Runtime error: expected the system to be little-endian!";
function I(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b();else{var d=b.H;"number"===typeof d?void 0===b.m?c.dynCall_v(d):c.dynCall_vi(d,b.m):d(void 0===b.m?null:b.m)}}}var wa=[],xa=[],ya=[],za=[],Aa=[],Ba=!1;function Ca(){var a=c.preRun.shift();wa.unshift(a)}var Da=Math.abs,Ea=Math.trunc,J=0,Fa=null,K=null;c.preloadedImages={};c.preloadedAudios={};
function L(a){return String.prototype.startsWith?a.startsWith("data:application/octet-stream;base64,"):0===a.indexOf("data:application/octet-stream;base64,")}
(function(){function a(){try{if(c.wasmBinary)return new Uint8Array(c.wasmBinary);if(c.readBinary)return c.readBinary(g);throw"on the web, we need the wasm binary to be preloaded and set on Module['wasmBinary']. emcc.py will do that for you when generating HTML (but not JS)";}catch(p){B(p)}}function b(){return c.wasmBinary||!n&&!q||"function"!==typeof fetch?new Promise(function(b){b(a())}):fetch(g,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+g+
"'";return a.arrayBuffer()}).catch(function(){return a()})}function d(a){function d(a){l=a.exports;if(l.memory){a=l.memory;var b=c.buffer;a.byteLength<b.byteLength&&c.printErr("the new buffer in mergeMemory is smaller than the previous one. in native wasm, we should grow memory here");b=new Int8Array(b);(new Int8Array(a)).set(b);c.buffer=buffer=a;qa()}c.asm=l;c.usingWasm=!0;J--;c.monitorRunDependencies&&c.monitorRunDependencies(J);0==J&&(null!==Fa&&(clearInterval(Fa),Fa=null),K&&(a=K,K=null,a()))}
function e(a){d(a.instance)}function ua(a){b().then(function(a){return WebAssembly.instantiate(a,h)}).then(a).catch(function(a){c.printErr("failed to asynchronously prepare wasm: "+a);B(a)})}if("object"!==typeof WebAssembly)return c.printErr("no native wasm support detected"),!1;if(!(c.wasmMemory instanceof WebAssembly.Memory))return c.printErr("no native wasm Memory in use"),!1;a.memory=c.wasmMemory;h.global={NaN:NaN,Infinity:Infinity};h["global.Math"]=Math;h.env=a;J++;c.monitorRunDependencies&&
c.monitorRunDependencies(J);if(c.instantiateWasm)try{return c.instantiateWasm(h,d)}catch(bb){return c.printErr("Module.instantiateWasm callback failed with error: "+bb),!1}c.wasmBinary||"function"!==typeof WebAssembly.instantiateStreaming||L(g)||"function"!==typeof fetch?ua(e):WebAssembly.instantiateStreaming(fetch(g,{credentials:"same-origin"}),h).then(e).catch(function(a){c.printErr("wasm streaming compile failed: "+a);c.printErr("falling back to ArrayBuffer instantiation");ua(e)});return{}}var e=
"WasmEncoder1.wast",g="WasmEncoder1.wasm",k="WasmEncoder1.temp.asm.js";"function"===typeof c.locateFile&&(L(e)||(e=c.locateFile(e)),L(g)||(g=c.locateFile(g)),L(k)||(k=c.locateFile(k)));var h={global:null,env:null,asm2wasm:{"f64-rem":function(a,b){return a%b},"debugger":function(){debugger}},parent:c},l=null;c.asmPreload=c.asm;var t=c.reallocBuffer;c.reallocBuffer=function(a){if("asmjs"===u)var b=t(a);else a:{var d=c.usingWasm?65536:16777216;0<a%d&&(a+=d-a%d);d=c.buffer.byteLength;if(c.usingWasm)try{b=
-1!==c.wasmMemory.grow((a-d)/65536)?c.buffer=c.wasmMemory.buffer:null;break a}catch(ua){b=null;break a}b=void 0}return b};var u="";c.asm=function(a,b){if(!b.table){a=c.wasmTableSize;void 0===a&&(a=1024);var e=c.wasmMaxTableSize;b.table="object"===typeof WebAssembly&&"function"===typeof WebAssembly.Table?void 0!==e?new WebAssembly.Table({initial:a,maximum:e,element:"anyfunc"}):new WebAssembly.Table({initial:a,element:"anyfunc"}):Array(a);c.wasmTable=b.table}b.memoryBase||(b.memoryBase=c.STATIC_BASE);
b.tableBase||(b.tableBase=0);(b=d(b))||B("no binaryen method succeeded. consider enabling more options, like interpreting, if you want that: https://github.com/kripken/emscripten/wiki/WebAssembly#binaryen-methods");return b}})();G=1024;x=G+2258848;xa.push();c.STATIC_BASE=G;c.STATIC_BUMP=2258848;x+=16;var M=0;function N(){M+=4;return z[M-4>>2]}var O={};
function P(a,b){M=b;try{var d=N(),e=N(),g=N();a=0;P.b||(P.b=[null,[],[]],P.v=function(a,b){var d=P.b[a];assert(d);0===b||10===b?((1===a?c.print:c.printErr)(la(d,0)),d.length=0):d.push(b)});for(b=0;b<g;b++){for(var k=z[e+8*b>>2],h=z[e+(8*b+4)>>2],l=0;l<h;l++)P.v(d,E[k+l]);a+=h}return a}catch(t){return"undefined"!==typeof FS&&t instanceof FS.c||B(t),-t.f}}function Ga(a){c.___errno_location&&(z[c.___errno_location()>>2]=a);return a}
function Q(){void 0===Q.start&&(Q.start=Date.now());return 1E3*(Date.now()-Q.start)|0}function R(){B()}var Ha=x;x+=16;var Ia,S={};function T(a){if(0===a)return 0;a=F(a);if(!S.hasOwnProperty(a))return 0;T.b&&La(T.b);a=S[a];var b=oa(a)+1,d=ja(b);d&&na(a,D,d,b);T.b=d;return T.b}var Ma=C(U("GMT"),2);
C([8,0,1,0,2,0,1,0,3,0,1,0,2,0,1,0,4,0,1,0,2,0,1,0,3,0,1,0,2,0,1,0,5,0,1,0,2,0,1,0,3,0,1,0,2,0,1,0,4,0,1,0,2,0,1,0,3,0,1,0,2,0,1,0,6,0,1,0,2,0,1,0,3,0,1,0,2,0,1,0,4,0,1,0,2,0,1,0,3,0,1,0,2,0,1,0,5,0,1,0,2,0,1,0,3,0,1,0,2,0,1,0,4,0,1,0,2,0,1,0,3,0,1,0,2,0,1,0,7,0,1,0,2,0,1,0,3,0,1,0,2,0,1,0,4,0,1,0,2,0,1,0,3,0,1,0,2,0,1,0,5,0,1,0,2,0,1,0,3,0,1,0,2,0,1,0,4,0,1,0,2,0,1,0,3,0,1,0,2,0,1,0,6,0,1,0,2,0,1,0,3,0,1,0,2,0,1,0,4,0,1,0,2,0,1,0,3,0,1,0,2,0,1,0,5,0,1,0,2,0,1,0,3,0,1,0,2,0,1,0,4,0,1,0,2,0,1,0,3,
0,1,0,2,0,1,0],2);function Na(a){return Math.pow(2,a)}function V(){V.b||(V.b=[]);V.b.push(Oa());return V.b.length-1}var W=x,Pa=x+=16,Qa=x+=16;x+=16;
function Ra(){function a(a){return(a=a.toTimeString().match(/\(([A-Za-z ]+)\)$/))?a[1]:"GMT"}if(!Sa){Sa=!0;z[Qa>>2]=60*(new Date).getTimezoneOffset();var b=new Date(2E3,0,1),d=new Date(2E3,6,1);z[Pa>>2]=Number(b.getTimezoneOffset()!=d.getTimezoneOffset());var e=a(b),g=a(d);e=C(U(e),0);g=C(U(g),0);d.getTimezoneOffset()<b.getTimezoneOffset()?(z[W>>2]=e,z[W+4>>2]=g):(z[W>>2]=g,z[W+4>>2]=e)}}var Sa;function X(a){return 0===a%4&&(0!==a%100||0===a%400)}
function Ta(a,b){for(var d=0,e=0;e<=b;d+=a[e++]);return d}var Ua=[31,29,31,30,31,30,31,31,30,31,30,31],Va=[31,28,31,30,31,30,31,31,30,31,30,31];function Wa(a,b){for(a=new Date(a.getTime());0<b;){var d=a.getMonth(),e=(X(a.getFullYear())?Ua:Va)[d];if(b>e-a.getDate())b-=e-a.getDate()+1,a.setDate(1),11>d?a.setMonth(d+1):(a.setMonth(0),a.setFullYear(a.getFullYear()+1));else{a.setDate(a.getDate()+b);break}}return a}
r?R=function(){var a=process.hrtime();return 1E3*a[0]+a[1]/1E6}:"undefined"!==typeof dateNow?R=dateNow:"object"===typeof self&&self.performance&&"function"===typeof self.performance.now?R=function(){return self.performance.now()}:"object"===typeof performance&&"function"===typeof performance.now?R=function(){return performance.now()}:R=Date.now;var Y,Z;
Ia?(Z=z[Ha>>2],Y=z[Z>>2]):(Ia=!0,S.USER=S.LOGNAME="web_user",S.PATH="/",S.PWD="/",S.HOME="/home/web_user",S.LANG="C.UTF-8",S._=c.thisProgram,Y=w(1024),Z=w(256),z[Z>>2]=Y,z[Ha>>2]=Z);var Xa=[],Ya=0,Za;for(Za in S)if("string"===typeof S[Za]){var $a=Za+"="+S[Za];Xa.push($a);Ya+=$a.length}if(1024<Ya)throw Error("Environment size exceeded TOTAL_ENV_SIZE!");
for(var ab=0;ab<Xa.length;ab++){for(var cb=$a=Xa[ab],db=Y,eb=0;eb<cb.length;++eb)D[db++>>0]=cb.charCodeAt(eb);D[db>>0]=0;z[Z+4*ab>>2]=Y;Y+=$a.length+1}z[Z+4*Xa.length>>2]=0;y=w(4);ra=H=ha(x);sa=ra+va;ta=ha(sa);z[y>>2]=ta;da=!0;function U(a,b){var d=Array(oa(a)+1);a=na(a,d,0,d.length);b&&(d.length=a);return d}c.wasmTableSize=1929;c.wasmMaxTableSize=1929;c.s={};
c.u={abort:B,enlargeMemory:function(){fa()},getTotalMemory:function(){return A},abortOnCannotGrowMemory:fa,invoke_dd:function(a,b){try{return c.dynCall_dd(a,b)}catch(d){if("number"!==typeof d&&"longjmp"!==d)throw d;c.setThrew(1,0)}},invoke_ddd:function(a,b,d){try{return c.dynCall_ddd(a,b,d)}catch(e){if("number"!==typeof e&&"longjmp"!==e)throw e;c.setThrew(1,0)}},invoke_iii:function(a,b,d){try{return c.dynCall_iii(a,b,d)}catch(e){if("number"!==typeof e&&"longjmp"!==e)throw e;c.setThrew(1,0)}},invoke_iiii:function(a,
b,d,e){try{return c.dynCall_iiii(a,b,d,e)}catch(g){if("number"!==typeof g&&"longjmp"!==g)throw g;c.setThrew(1,0)}},invoke_jiiiiii:function(a,b,d,e,g,k,h){try{return c.dynCall_jiiiiii(a,b,d,e,g,k,h)}catch(l){if("number"!==typeof l&&"longjmp"!==l)throw l;c.setThrew(1,0)}},invoke_vi:function(a,b){try{c.dynCall_vi(a,b)}catch(d){if("number"!==typeof d&&"longjmp"!==d)throw d;c.setThrew(1,0)}},invoke_vii:function(a,b,d){try{c.dynCall_vii(a,b,d)}catch(e){if("number"!==typeof e&&"longjmp"!==e)throw e;c.setThrew(1,
0)}},invoke_viiii:function(a,b,d,e,g){try{c.dynCall_viiii(a,b,d,e,g)}catch(k){if("number"!==typeof k&&"longjmp"!==k)throw k;c.setThrew(1,0)}},invoke_viiiii:function(a,b,d,e,g,k){try{c.dynCall_viiiii(a,b,d,e,g,k)}catch(h){if("number"!==typeof h&&"longjmp"!==h)throw h;c.setThrew(1,0)}},invoke_vijjjid:function(a,b,d,e,g,k,h,l,t,u){try{c.dynCall_vijjjid(a,b,d,e,g,k,h,l,t,u)}catch(p){if("number"!==typeof p&&"longjmp"!==p)throw p;c.setThrew(1,0)}},___assert_fail:function(a,b,d,e){B("Assertion failed: "+
F(a)+", at: "+[b?F(b):"unknown filename",d,e?F(e):"unknown function"])},___lock:function(){},___setErrNo:Ga,___syscall140:function(a,b){M=b;try{var d=O.i();N();var e=N(),g=N(),k=N();FS.I(d,e,k);z[g>>2]=d.position;d.A&&0===e&&0===k&&(d.A=null);return 0}catch(h){return"undefined"!==typeof FS&&h instanceof FS.c||B(h),-h.f}},___syscall145:function(a,b){M=b;try{var d=O.i(),e=N(),g=N();return O.G(d,e,g)}catch(k){return"undefined"!==typeof FS&&k instanceof FS.c||B(k),-k.f}},___syscall146:P,___syscall195:function(a,
b){M=b;try{var d=F(N()),e=N();return O.w(FS.stat,d,e)}catch(g){return"undefined"!==typeof FS&&g instanceof FS.c||B(g),-g.f}},___syscall197:function(a,b){M=b;try{var d=O.i(),e=N();return O.w(FS.stat,d.path,e)}catch(g){return"undefined"!==typeof FS&&g instanceof FS.c||B(g),-g.f}},___syscall219:function(a,b){M=b;return 0},___syscall221:function(a,b){M=b;return 0},___syscall3:function(a,b){M=b;try{var d=O.i(),e=N(),g=N();return FS.read(d,D,e,g)}catch(k){return"undefined"!==typeof FS&&k instanceof FS.c||
B(k),-k.f}},___syscall38:function(a,b){M=b;try{var d=F(N()),e=F(N());FS.rename(d,e);return 0}catch(g){return"undefined"!==typeof FS&&g instanceof FS.c||B(g),-g.f}},___syscall5:function(a,b){M=b;try{var d=F(N()),e=N(),g=N();return FS.open(d,e,g).fd}catch(k){return"undefined"!==typeof FS&&k instanceof FS.c||B(k),-k.f}},___syscall54:function(a,b){M=b;return 0},___syscall6:function(a,b){M=b;try{var d=O.i();FS.close(d);return 0}catch(e){return"undefined"!==typeof FS&&e instanceof FS.c||B(e),-e.f}},___unlock:function(){},
_abort:function(){c.abort()},_clock:Q,_clock_gettime:function(a,b){if(0===a)a=Date.now();else if(1===a&&(r||"undefined"!==typeof dateNow||(n||q)&&self.performance&&self.performance.now))a=R();else return Ga(22),-1;z[b>>2]=a/1E3|0;z[b+4>>2]=a%1E3*1E6|0;return 0},_emscripten_memcpy_big:function(a,b,d){E.set(E.subarray(b,b+d),a);return a},_exit:function(a){c.exit(a)},_fabs:Da,_getenv:T,_gettimeofday:function(a){var b=Date.now();z[a>>2]=b/1E3|0;z[a+4>>2]=b%1E3*1E3|0;return 0},_gmtime_r:function(a,b){a=
new Date(1E3*z[a>>2]);z[b>>2]=a.getUTCSeconds();z[b+4>>2]=a.getUTCMinutes();z[b+8>>2]=a.getUTCHours();z[b+12>>2]=a.getUTCDate();z[b+16>>2]=a.getUTCMonth();z[b+20>>2]=a.getUTCFullYear()-1900;z[b+24>>2]=a.getUTCDay();z[b+36>>2]=0;z[b+32>>2]=0;z[b+28>>2]=(a.getTime()-Date.UTC(a.getUTCFullYear(),0,1,0,0,0,0))/864E5|0;z[b+40>>2]=Ma;return b},_llvm_exp2_f32:Na,_llvm_exp2_f64:function(){return Na.apply(null,arguments)},_llvm_stackrestore:function(a){var b=V.b[a];V.b.splice(a,1);fb(b)},_llvm_stacksave:V,
_llvm_trunc_f64:Ea,_localtime_r:function(a,b){Ra();a=new Date(1E3*z[a>>2]);z[b>>2]=a.getSeconds();z[b+4>>2]=a.getMinutes();z[b+8>>2]=a.getHours();z[b+12>>2]=a.getDate();z[b+16>>2]=a.getMonth();z[b+20>>2]=a.getFullYear()-1900;z[b+24>>2]=a.getDay();var d=new Date(a.getFullYear(),0,1);z[b+28>>2]=(a.getTime()-d.getTime())/864E5|0;z[b+36>>2]=-(60*a.getTimezoneOffset());var e=(new Date(2E3,6,1)).getTimezoneOffset();d=d.getTimezoneOffset();a=(e!=d&&a.getTimezoneOffset()==Math.min(d,e))|0;z[b+32>>2]=a;z[b+
40>>2]=z[W+(a?4:0)>>2];return b},_longjmp:function(a,b){c.setThrew(a,b||1);throw"longjmp";},_mktime:function(a){Ra();var b=new Date(z[a+20>>2]+1900,z[a+16>>2],z[a+12>>2],z[a+8>>2],z[a+4>>2],z[a>>2],0),d=z[a+32>>2],e=b.getTimezoneOffset(),g=new Date(b.getFullYear(),0,1),k=(new Date(2E3,6,1)).getTimezoneOffset(),h=g.getTimezoneOffset(),l=Math.min(h,k);0>d?z[a+32>>2]=Number(k!=h&&l==e):0<d!=(l==e)&&(k=Math.max(h,k),b.setTime(b.getTime()+6E4*((0<d?l:k)-e)));z[a+24>>2]=b.getDay();z[a+28>>2]=(b.getTime()-
g.getTime())/864E5|0;return b.getTime()/1E3|0},_nanosleep:function(a,b){var d=z[a>>2];a=z[a+4>>2];0!==b&&(z[b>>2]=0,z[b+4>>2]=0);b=(1E6*d+a/1E3)/1E3;if((n||q)&&self.performance&&self.performance.now)for(d=self.performance.now();self.performance.now()-d<b;);else for(d=Date.now();Date.now()-d<b;);return 0},_strftime:function(a,b,d,e){function g(a,b,d){for(a="number"===typeof a?a.toString():a||"";a.length<b;)a=d[0]+a;return a}function k(a,b){return g(a,b,"0")}function h(a,b){function d(a){return 0>a?
-1:0<a?1:0}var e;0===(e=d(a.getFullYear()-b.getFullYear()))&&0===(e=d(a.getMonth()-b.getMonth()))&&(e=d(a.getDate()-b.getDate()));return e}function l(a){switch(a.getDay()){case 0:return new Date(a.getFullYear()-1,11,29);case 1:return a;case 2:return new Date(a.getFullYear(),0,3);case 3:return new Date(a.getFullYear(),0,2);case 4:return new Date(a.getFullYear(),0,1);case 5:return new Date(a.getFullYear()-1,11,31);case 6:return new Date(a.getFullYear()-1,11,30)}}function t(a){a=Wa(new Date(a.a+1900,
0,1),a.l);var b=l(new Date(a.getFullYear()+1,0,4));return 0>=h(l(new Date(a.getFullYear(),0,4)),a)?0>=h(b,a)?a.getFullYear()+1:a.getFullYear():a.getFullYear()-1}var u=z[e+40>>2];e={D:z[e>>2],C:z[e+4>>2],j:z[e+8>>2],h:z[e+12>>2],g:z[e+16>>2],a:z[e+20>>2],o:z[e+24>>2],l:z[e+28>>2],J:z[e+32>>2],B:z[e+36>>2],F:u?F(u):""};d=F(d);u={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S","%x":"%m/%d/%y","%X":"%H:%M:%S"};for(var p in u)d=d.replace(new RegExp(p,
"g"),u[p]);var Ja="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),Ka="January February March April May June July August September October November December".split(" ");u={"%a":function(a){return Ja[a.o].substring(0,3)},"%A":function(a){return Ja[a.o]},"%b":function(a){return Ka[a.g].substring(0,3)},"%B":function(a){return Ka[a.g]},"%C":function(a){return k((a.a+1900)/100|0,2)},"%d":function(a){return k(a.h,2)},"%e":function(a){return g(a.h,2," ")},"%g":function(a){return t(a).toString().substring(2)},
"%G":function(a){return t(a)},"%H":function(a){return k(a.j,2)},"%I":function(a){a=a.j;0==a?a=12:12<a&&(a-=12);return k(a,2)},"%j":function(a){return k(a.h+Ta(X(a.a+1900)?Ua:Va,a.g-1),3)},"%m":function(a){return k(a.g+1,2)},"%M":function(a){return k(a.C,2)},"%n":function(){return"\n"},"%p":function(a){return 0<=a.j&&12>a.j?"AM":"PM"},"%S":function(a){return k(a.D,2)},"%t":function(){return"\t"},"%u":function(a){return(new Date(a.a+1900,a.g+1,a.h,0,0,0,0)).getDay()||7},"%U":function(a){var b=new Date(a.a+
1900,0,1),d=0===b.getDay()?b:Wa(b,7-b.getDay());a=new Date(a.a+1900,a.g,a.h);return 0>h(d,a)?k(Math.ceil((31-d.getDate()+(Ta(X(a.getFullYear())?Ua:Va,a.getMonth()-1)-31)+a.getDate())/7),2):0===h(d,b)?"01":"00"},"%V":function(a){var b=l(new Date(a.a+1900,0,4)),d=l(new Date(a.a+1901,0,4)),e=Wa(new Date(a.a+1900,0,1),a.l);return 0>h(e,b)?"53":0>=h(d,e)?"01":k(Math.ceil((b.getFullYear()<a.a+1900?a.l+32-b.getDate():a.l+1-b.getDate())/7),2)},"%w":function(a){return(new Date(a.a+1900,a.g+1,a.h,0,0,0,0)).getDay()},
"%W":function(a){var b=new Date(a.a,0,1),d=1===b.getDay()?b:Wa(b,0===b.getDay()?1:7-b.getDay()+1);a=new Date(a.a+1900,a.g,a.h);return 0>h(d,a)?k(Math.ceil((31-d.getDate()+(Ta(X(a.getFullYear())?Ua:Va,a.getMonth()-1)-31)+a.getDate())/7),2):0===h(d,b)?"01":"00"},"%y":function(a){return(a.a+1900).toString().substring(2)},"%Y":function(a){return a.a+1900},"%z":function(a){a=a.B;var b=0<=a;a=Math.abs(a)/60;return(b?"+":"-")+String("0000"+(a/60*100+a%60)).slice(-4)},"%Z":function(a){return a.F},"%%":function(){return"%"}};
for(p in u)0<=d.indexOf(p)&&(d=d.replace(new RegExp(p,"g"),u[p](e)));p=U(d,!1);if(p.length>b)return 0;D.set(p,a);return p.length-1},_time:function(a){var b=Date.now()/1E3|0;a&&(z[a>>2]=b);return b},DYNAMICTOP_PTR:y,STACKTOP:H};var gb=c.asm(c.s,c.u,buffer);c.asm=gb;c._add_audio_frame=function(){return c.asm._add_audio_frame.apply(null,arguments)};c._add_video_frame=function(){return c.asm._add_video_frame.apply(null,arguments)};c._close_stream=function(){return c.asm._close_stream.apply(null,arguments)};
var La=c._free=function(){return c.asm._free.apply(null,arguments)};c._free_buffer=function(){return c.asm._free_buffer.apply(null,arguments)};var ja=c._malloc=function(){return c.asm._malloc.apply(null,arguments)};c._open_audio=function(){return c.asm._open_audio.apply(null,arguments)};c._open_video=function(){return c.asm._open_video.apply(null,arguments)};c._write_header=function(){return c.asm._write_header.apply(null,arguments)};c.setThrew=function(){return c.asm.setThrew.apply(null,arguments)};
var ka=c.stackAlloc=function(){return c.asm.stackAlloc.apply(null,arguments)},fb=c.stackRestore=function(){return c.asm.stackRestore.apply(null,arguments)},Oa=c.stackSave=function(){return c.asm.stackSave.apply(null,arguments)};c.dynCall_dd=function(){return c.asm.dynCall_dd.apply(null,arguments)};c.dynCall_ddd=function(){return c.asm.dynCall_ddd.apply(null,arguments)};c.dynCall_iii=function(){return c.asm.dynCall_iii.apply(null,arguments)};
c.dynCall_iiii=function(){return c.asm.dynCall_iiii.apply(null,arguments)};c.dynCall_jiiiiii=function(){return c.asm.dynCall_jiiiiii.apply(null,arguments)};c.dynCall_v=function(){return c.asm.dynCall_v.apply(null,arguments)};c.dynCall_vi=function(){return c.asm.dynCall_vi.apply(null,arguments)};c.dynCall_vii=function(){return c.asm.dynCall_vii.apply(null,arguments)};c.dynCall_viiii=function(){return c.asm.dynCall_viiii.apply(null,arguments)};
c.dynCall_viiiii=function(){return c.asm.dynCall_viiiii.apply(null,arguments)};c.dynCall_vijjjid=function(){return c.asm.dynCall_vijjjid.apply(null,arguments)};c.asm=gb;c.then=function(a){if(c.calledRun)a(c);else{var b=c.onRuntimeInitialized;c.onRuntimeInitialized=function(){b&&b();a(c)}}return c};function v(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}v.prototype=Error();v.prototype.constructor=v;K=function hb(){c.calledRun||ib();c.calledRun||(K=hb)};
function ib(){function a(){if(!c.calledRun&&(c.calledRun=!0,!ia)){Ba||(Ba=!0,I(xa));I(ya);if(c.onRuntimeInitialized)c.onRuntimeInitialized();if(c.postRun)for("function"==typeof c.postRun&&(c.postRun=[c.postRun]);c.postRun.length;){var a=c.postRun.shift();Aa.unshift(a)}I(Aa)}}if(!(0<J)){if(c.preRun)for("function"==typeof c.preRun&&(c.preRun=[c.preRun]);c.preRun.length;)Ca();I(wa);0<J||c.calledRun||(c.setStatus?(c.setStatus("Running..."),setTimeout(function(){setTimeout(function(){c.setStatus("")},
1);a()},1)):a())}}c.run=ib;c.exit=function(a,b){if(!b||!c.noExitRuntime||0!==a){if(!c.noExitRuntime&&(ia=!0,H=void 0,I(za),c.onExit))c.onExit(a);r&&process.exit(a);c.quit(a,new v(a))}};function B(a){if(c.onAbort)c.onAbort(a);void 0!==a?(c.print(a),c.printErr(a),a=JSON.stringify(a)):a="";ia=!0;throw"abort("+a+"). Build with -s ASSERTIONS=1 for more info.";}c.abort=B;if(c.preInit)for("function"==typeof c.preInit&&(c.preInit=[c.preInit]);0<c.preInit.length;)c.preInit.pop()();c.noExitRuntime=!0;ib();


  return WasmEncoder1;
};
if (typeof exports === 'object' && typeof module === 'object')
  module.exports = WasmEncoder1;
else if (typeof define === 'function' && define['amd'])
  define([], function() { return WasmEncoder1; });
else if (typeof exports === 'object')
  exports["WasmEncoder1"] = WasmEncoder1;
