var WasmVideoEncoderTest2 = function(WasmVideoEncoderTest2) {
  WasmVideoEncoderTest2 = WasmVideoEncoderTest2 || {};

var c;c||(c=typeof WasmVideoEncoderTest2 !== 'undefined' ? WasmVideoEncoderTest2 : {});var f={},l;for(l in c)c.hasOwnProperty(l)&&(f[l]=c[l]);c.arguments=[];c.thisProgram="./this.program";c.quit=function(a,b){throw b;};c.preRun=[];c.postRun=[];var n=!1,p=!1,q=!1,aa=!1;
if(c.ENVIRONMENT)if("WEB"===c.ENVIRONMENT)n=!0;else if("WORKER"===c.ENVIRONMENT)p=!0;else if("NODE"===c.ENVIRONMENT)q=!0;else if("SHELL"===c.ENVIRONMENT)aa=!0;else throw Error("Module['ENVIRONMENT'] value is not valid. must be one of: WEB|WORKER|NODE|SHELL.");else n="object"===typeof window,p="function"===typeof importScripts,q="object"===typeof process&&"function"===typeof require&&!n&&!p,aa=!n&&!q&&!p;
if(q){var ba,ca;c.read=function(a,b){ba||(ba=require("fs"));ca||(ca=require("path"));a=ca.normalize(a);a=ba.readFileSync(a);return b?a:a.toString()};c.readBinary=function(a){a=c.read(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a};1<process.argv.length&&(c.thisProgram=process.argv[1].replace(/\\/g,"/"));c.arguments=process.argv.slice(2);process.on("uncaughtException",function(a){if(!(a instanceof u))throw a;});process.on("unhandledRejection",function(){process.exit(1)});c.inspect=
function(){return"[Emscripten Module object]"}}else if(aa)"undefined"!=typeof read&&(c.read=function(a){return read(a)}),c.readBinary=function(a){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(a));a=read(a,"binary");assert("object"===typeof a);return a},"undefined"!=typeof scriptArgs?c.arguments=scriptArgs:"undefined"!=typeof arguments&&(c.arguments=arguments),"function"===typeof quit&&(c.quit=function(a){quit(a)});else if(n||p)c.read=function(a){var b=new XMLHttpRequest;b.open("GET",
a,!1);b.send(null);return b.responseText},p&&(c.readBinary=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),c.readAsync=function(a,b,e){var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=function(){200==d.status||0==d.status&&d.response?b(d.response):e()};d.onerror=e;d.send(null)},"undefined"!=typeof arguments&&(c.arguments=arguments),c.setWindowTitle=function(a){document.title=a};
c.print="undefined"!==typeof console?console.log.bind(console):"undefined"!==typeof print?print:null;c.printErr="undefined"!==typeof printErr?printErr:"undefined"!==typeof console&&console.warn.bind(console)||c.print;c.print=c.print;c.printErr=c.printErr;for(l in f)f.hasOwnProperty(l)&&(c[l]=f[l]);f=void 0;function v(a){assert(!da);var b=x;x=x+a+15&-16;return b}function ea(a){assert(y);var b=z[y>>2];a=b+a+15&-16;z[y>>2]=a;return a>=A&&!fa()?(z[y>>2]=b,0):b}
function ha(a){var b;b||(b=16);return Math.ceil(a/b)*b}var ia=0;function assert(a,b){a||B("Assertion failed: "+b)}function C(a,b){if("number"===typeof a){var e=!0;var d=a}else e=!1,d=a.length;b=4==b?g:["function"===typeof ja?ja:v,ka,v,ea][void 0===b?2:b](Math.max(d,1));if(e){var g=b;assert(0==(b&3));for(a=b+(d&-4);g<a;g+=4)z[g>>2]=0;for(a=b+d;g<a;)D[g++>>0]=0;return b}a.subarray||a.slice?E.set(a,b):E.set(new Uint8Array(a),b);return b}
function F(a){var b;if(0===b||!a)return"";for(var e=0,d,g=0;;){d=E[a+g>>0];e|=d;if(0==d&&!b)break;g++;if(b&&g==b)break}b||(b=g);d="";if(128>e){for(;0<b;)e=String.fromCharCode.apply(String,E.subarray(a,a+Math.min(b,1024))),d=d?d+e:e,a+=1024,b-=1024;return d}return la(E,a)}var ma="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function la(a,b){for(var e=b;a[e];)++e;if(16<e-b&&a.subarray&&ma)return ma.decode(a.subarray(b,e));for(e="";;){var d=a[b++];if(!d)return e;if(d&128){var g=a[b++]&63;if(192==(d&224))e+=String.fromCharCode((d&31)<<6|g);else{var h=a[b++]&63;if(224==(d&240))d=(d&15)<<12|g<<6|h;else{var k=a[b++]&63;if(240==(d&248))d=(d&7)<<18|g<<12|h<<6|k;else{var m=a[b++]&63;if(248==(d&252))d=(d&3)<<24|g<<18|h<<12|k<<6|m;else{var r=a[b++]&63;d=(d&1)<<30|g<<24|h<<18|k<<12|m<<6|r}}}65536>d?e+=String.fromCharCode(d):(d-=
65536,e+=String.fromCharCode(55296|d>>10,56320|d&1023))}}else e+=String.fromCharCode(d)}}
function na(a,b,e,d){if(!(0<d))return 0;var g=e;d=e+d-1;for(var h=0;h<a.length;++h){var k=a.charCodeAt(h);55296<=k&&57343>=k&&(k=65536+((k&1023)<<10)|a.charCodeAt(++h)&1023);if(127>=k){if(e>=d)break;b[e++]=k}else{if(2047>=k){if(e+1>=d)break;b[e++]=192|k>>6}else{if(65535>=k){if(e+2>=d)break;b[e++]=224|k>>12}else{if(2097151>=k){if(e+3>=d)break;b[e++]=240|k>>18}else{if(67108863>=k){if(e+4>=d)break;b[e++]=248|k>>24}else{if(e+5>=d)break;b[e++]=252|k>>30;b[e++]=128|k>>24&63}b[e++]=128|k>>18&63}b[e++]=128|
k>>12&63}b[e++]=128|k>>6&63}b[e++]=128|k&63}}b[e]=0;return e-g}function oa(a){for(var b=0,e=0;e<a.length;++e){var d=a.charCodeAt(e);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++e)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:2097151>=d?b+4:67108863>=d?b+5:b+6}return b}"undefined"!==typeof TextDecoder&&new TextDecoder("utf-16le");var pa=65536,qa=16777216,ra=16777216;function sa(a,b){0<a%b&&(a+=b-a%b);return a}var buffer,D,E,ta,z;
function ua(){c.HEAP8=D=new Int8Array(buffer);c.HEAP16=ta=new Int16Array(buffer);c.HEAP32=z=new Int32Array(buffer);c.HEAPU8=E=new Uint8Array(buffer);c.HEAPU16=new Uint16Array(buffer);c.HEAPU32=new Uint32Array(buffer);c.HEAPF32=new Float32Array(buffer);c.HEAPF64=new Float64Array(buffer)}var G,x,da,va,H,wa,xa,y;G=x=va=H=wa=xa=y=0;da=!1;
c.reallocBuffer||(c.reallocBuffer=function(a){try{if(ArrayBuffer.G)var b=ArrayBuffer.G(buffer,a);else{var e=D;b=new ArrayBuffer(a);(new Int8Array(b)).set(e)}}catch(d){return!1}return ya(b)?b:!1});function fa(){var a=c.usingWasm?pa:qa,b=2147483648-a;if(z[y>>2]>b)return!1;var e=A;for(A=Math.max(A,ra);A<z[y>>2];)536870912>=A?A=sa(2*A,a):A=Math.min(sa((3*A+2147483648)/4,a),b);a=c.reallocBuffer(A);if(!a||a.byteLength!=A)return A=e,!1;c.buffer=buffer=a;ua();return!0}var Aa;
try{Aa=Function.prototype.call.bind(Object.getOwnPropertyDescriptor(ArrayBuffer.prototype,"byteLength").get),Aa(new ArrayBuffer(4))}catch(a){Aa=function(b){return b.byteLength}}var Ba=c.TOTAL_STACK||5242880,A=c.TOTAL_MEMORY||16777216;A<Ba&&c.printErr("TOTAL_MEMORY should be larger than TOTAL_STACK, was "+A+"! (TOTAL_STACK="+Ba+")");
c.buffer?buffer=c.buffer:("object"===typeof WebAssembly&&"function"===typeof WebAssembly.Memory?(c.wasmMemory=new WebAssembly.Memory({initial:A/pa}),buffer=c.wasmMemory.buffer):buffer=new ArrayBuffer(A),c.buffer=buffer);ua();z[0]=1668509029;ta[1]=25459;if(115!==E[2]||99!==E[3])throw"Runtime error: expected the system to be little-endian!";
function I(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b();else{var e=b.J;"number"===typeof e?void 0===b.o?c.dynCall_v(e):c.dynCall_vi(e,b.o):e(void 0===b.o?null:b.o)}}}var Ca=[],Da=[],Ea=[],Fa=[],Ga=[],Ha=!1;function Ia(){var a=c.preRun.shift();Ca.unshift(a)}var Ja=Math.abs,Ka=Math.trunc,J=0,La=null,K=null;c.preloadedImages={};c.preloadedAudios={};
function L(a){return String.prototype.startsWith?a.startsWith("data:application/octet-stream;base64,"):0===a.indexOf("data:application/octet-stream;base64,")}
(function(){function a(){try{if(c.wasmBinary)return new Uint8Array(c.wasmBinary);if(c.readBinary)return c.readBinary(g);throw"on the web, we need the wasm binary to be preloaded and set on Module['wasmBinary']. emcc.py will do that for you when generating HTML (but not JS)";}catch(w){B(w)}}function b(){return c.wasmBinary||!n&&!p||"function"!==typeof fetch?new Promise(function(b){b(a())}):fetch(g,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+g+
"'";return a.arrayBuffer()}).catch(function(){return a()})}function e(a){function e(a){m=a.exports;if(m.memory){a=m.memory;var b=c.buffer;a.byteLength<b.byteLength&&c.printErr("the new buffer in mergeMemory is smaller than the previous one. in native wasm, we should grow memory here");b=new Int8Array(b);(new Int8Array(a)).set(b);c.buffer=buffer=a;ua()}c.asm=m;c.usingWasm=!0;J--;c.monitorRunDependencies&&c.monitorRunDependencies(J);0==J&&(null!==La&&(clearInterval(La),La=null),K&&(a=K,K=null,a()))}
function d(a){e(a.instance)}function za(a){b().then(function(a){return WebAssembly.instantiate(a,k)}).then(a).catch(function(a){c.printErr("failed to asynchronously prepare wasm: "+a);B(a)})}if("object"!==typeof WebAssembly)return c.printErr("no native wasm support detected"),!1;if(!(c.wasmMemory instanceof WebAssembly.Memory))return c.printErr("no native wasm Memory in use"),!1;a.memory=c.wasmMemory;k.global={NaN:NaN,Infinity:Infinity};k["global.Math"]=Math;k.env=a;J++;c.monitorRunDependencies&&
c.monitorRunDependencies(J);if(c.instantiateWasm)try{return c.instantiateWasm(k,e)}catch(hb){return c.printErr("Module.instantiateWasm callback failed with error: "+hb),!1}c.wasmBinary||"function"!==typeof WebAssembly.instantiateStreaming||L(g)||"function"!==typeof fetch?za(d):WebAssembly.instantiateStreaming(fetch(g,{credentials:"same-origin"}),k).then(d).catch(function(a){c.printErr("wasm streaming compile failed: "+a);c.printErr("falling back to ArrayBuffer instantiation");za(d)});return{}}var d=
"WasmVideoEncoderTest2.wast",g="WasmVideoEncoderTest2.wasm",h="WasmVideoEncoderTest2.temp.asm.js";"function"===typeof c.locateFile&&(L(d)||(d=c.locateFile(d)),L(g)||(g=c.locateFile(g)),L(h)||(h=c.locateFile(h)));var k={global:null,env:null,asm2wasm:{"f64-rem":function(a,b){return a%b},"debugger":function(){debugger}},parent:c},m=null;c.asmPreload=c.asm;var r=c.reallocBuffer;c.reallocBuffer=function(a){if("asmjs"===t)var b=r(a);else a:{a=sa(a,c.usingWasm?pa:qa);var e=c.buffer.byteLength;if(c.usingWasm)try{b=
-1!==c.wasmMemory.grow((a-e)/65536)?c.buffer=c.wasmMemory.buffer:null;break a}catch(za){b=null;break a}b=void 0}return b};var t="";c.asm=function(a,b){if(!b.table){a=c.wasmTableSize;void 0===a&&(a=1024);var d=c.wasmMaxTableSize;b.table="object"===typeof WebAssembly&&"function"===typeof WebAssembly.Table?void 0!==d?new WebAssembly.Table({initial:a,maximum:d,element:"anyfunc"}):new WebAssembly.Table({initial:a,element:"anyfunc"}):Array(a);c.wasmTable=b.table}b.memoryBase||(b.memoryBase=c.STATIC_BASE);
b.tableBase||(b.tableBase=0);(b=e(b))||B("no binaryen method succeeded. consider enabling more options, like interpreting, if you want that: https://github.com/kripken/emscripten/wiki/WebAssembly#binaryen-methods");return b}})();G=1024;x=G+1357008;Da.push();c.STATIC_BASE=G;c.STATIC_BUMP=1357008;x+=16;var M=0;function N(){M+=4;return z[M-4>>2]}function O(){return F(N())}var P={};
function Q(a,b){M=b;try{var e=N(),d=N(),g=N();a=0;Q.h||(Q.h=[null,[],[]],Q.A=function(a,b){var d=Q.h[a];assert(d);0===b||10===b?((1===a?c.print:c.printErr)(la(d,0)),d.length=0):d.push(b)});for(b=0;b<g;b++){for(var h=z[d+8*b>>2],k=z[d+(8*b+4)>>2],m=0;m<k;m++)Q.A(e,E[h+m]);a+=k}return a}catch(r){return"undefined"!==typeof FS&&r instanceof FS.b||B(r),-r.c}}function Ma(a){c.___errno_location&&(z[c.___errno_location()>>2]=a);return a}
function R(){void 0===R.start&&(R.start=Date.now());return 1E3*(Date.now()-R.start)|0}function S(){B()}var Pa=x;x+=16;var Qa,T={};function U(a){if(0===a)return 0;a=F(a);if(!T.hasOwnProperty(a))return 0;U.h&&Ra(U.h);a=T[a];var b=oa(a)+1,e=ja(b);e&&na(a,D,e,b);U.h=e;return U.h}var Sa=C(V("GMT"),2);
C([8,0,1,0,2,0,1,0,3,0,1,0,2,0,1,0,4,0,1,0,2,0,1,0,3,0,1,0,2,0,1,0,5,0,1,0,2,0,1,0,3,0,1,0,2,0,1,0,4,0,1,0,2,0,1,0,3,0,1,0,2,0,1,0,6,0,1,0,2,0,1,0,3,0,1,0,2,0,1,0,4,0,1,0,2,0,1,0,3,0,1,0,2,0,1,0,5,0,1,0,2,0,1,0,3,0,1,0,2,0,1,0,4,0,1,0,2,0,1,0,3,0,1,0,2,0,1,0,7,0,1,0,2,0,1,0,3,0,1,0,2,0,1,0,4,0,1,0,2,0,1,0,3,0,1,0,2,0,1,0,5,0,1,0,2,0,1,0,3,0,1,0,2,0,1,0,4,0,1,0,2,0,1,0,3,0,1,0,2,0,1,0,6,0,1,0,2,0,1,0,3,0,1,0,2,0,1,0,4,0,1,0,2,0,1,0,3,0,1,0,2,0,1,0,5,0,1,0,2,0,1,0,3,0,1,0,2,0,1,0,4,0,1,0,2,0,1,0,3,
0,1,0,2,0,1,0],2);function Ta(a){return Math.pow(2,a)}var W=x,Ua=x+=16,Va=x+=16;x+=16;function Wa(){function a(a){return(a=a.toTimeString().match(/\(([A-Za-z ]+)\)$/))?a[1]:"GMT"}if(!Xa){Xa=!0;z[Va>>2]=60*(new Date).getTimezoneOffset();var b=new Date(2E3,0,1),e=new Date(2E3,6,1);z[Ua>>2]=Number(b.getTimezoneOffset()!=e.getTimezoneOffset());var d=a(b),g=a(e);d=C(V(d),0);g=C(V(g),0);e.getTimezoneOffset()<b.getTimezoneOffset()?(z[W>>2]=d,z[W+4>>2]=g):(z[W>>2]=g,z[W+4>>2]=d)}}var Xa;
function X(a){return 0===a%4&&(0!==a%100||0===a%400)}function Ya(a,b){for(var e=0,d=0;d<=b;e+=a[d++]);return e}var Za=[31,29,31,30,31,30,31,31,30,31,30,31],$a=[31,28,31,30,31,30,31,31,30,31,30,31];function ab(a,b){for(a=new Date(a.getTime());0<b;){var e=a.getMonth(),d=(X(a.getFullYear())?Za:$a)[e];if(b>d-a.getDate())b-=d-a.getDate()+1,a.setDate(1),11>e?a.setMonth(e+1):(a.setMonth(0),a.setFullYear(a.getFullYear()+1));else{a.setDate(a.getDate()+b);break}}return a}
q?S=function(){var a=process.hrtime();return 1E3*a[0]+a[1]/1E6}:"undefined"!==typeof dateNow?S=dateNow:"object"===typeof self&&self.performance&&"function"===typeof self.performance.now?S=function(){return self.performance.now()}:"object"===typeof performance&&"function"===typeof performance.now?S=function(){return performance.now()}:S=Date.now;var Y,Z;
Qa?(Z=z[Pa>>2],Y=z[Z>>2]):(Qa=!0,T.USER=T.LOGNAME="web_user",T.PATH="/",T.PWD="/",T.HOME="/home/web_user",T.LANG="C.UTF-8",T._=c.thisProgram,Y=v(1024),Z=v(256),z[Z>>2]=Y,z[Pa>>2]=Z);var bb=[],cb=0,db;for(db in T)if("string"===typeof T[db]){var eb=db+"="+T[db];bb.push(eb);cb+=eb.length}if(1024<cb)throw Error("Environment size exceeded TOTAL_ENV_SIZE!");
for(var fb=0;fb<bb.length;fb++){for(var gb=eb=bb[fb],ib=Y,jb=0;jb<gb.length;++jb)D[ib++>>0]=gb.charCodeAt(jb);D[ib>>0]=0;z[Z+4*fb>>2]=Y;Y+=eb.length+1}z[Z+4*bb.length>>2]=0;y=v(4);va=H=ha(x);wa=va+Ba;xa=ha(wa);z[y>>2]=xa;da=!0;function V(a,b){var e=Array(oa(a)+1);a=na(a,e,0,e.length);b&&(e.length=a);return e}c.wasmTableSize=1042;c.wasmMaxTableSize=1042;c.v={};
c.w={abort:B,enlargeMemory:fa,getTotalMemory:function(){return A},abortOnCannotGrowMemory:function(){B("Cannot enlarge memory arrays. Either (1) compile with  -s TOTAL_MEMORY=X  with X higher than the current value "+A+", (2) compile with  -s ALLOW_MEMORY_GROWTH=1  which allows increasing the size at runtime, or (3) if you want malloc to return NULL (0) instead of this abort, compile with  -s ABORTING_MALLOC=0 ")},___assert_fail:function(a,b,e,d){B("Assertion failed: "+F(a)+", at: "+[b?F(b):"unknown filename",
e,d?F(d):"unknown function"])},___lock:function(){},___setErrNo:Ma,___syscall10:function(a,b){M=b;try{var e=O();FS.unlink(e);return 0}catch(d){return"undefined"!==typeof FS&&d instanceof FS.b||B(d),-d.c}},___syscall140:function(a,b){M=b;try{var e=P.i();N();var d=N(),g=N(),h=N();FS.N(e,d,h);z[g>>2]=e.position;e.j&&0===d&&0===h&&(e.j=null);return 0}catch(k){return"undefined"!==typeof FS&&k instanceof FS.b||B(k),-k.c}},___syscall145:function(a,b){M=b;try{var e=P.i(),d=N(),g=N();return P.I(e,d,g)}catch(h){return"undefined"!==
typeof FS&&h instanceof FS.b||B(h),-h.c}},___syscall146:Q,___syscall195:function(a,b){M=b;try{var e=O(),d=N();return P.s(FS.stat,e,d)}catch(g){return"undefined"!==typeof FS&&g instanceof FS.b||B(g),-g.c}},___syscall196:function(a,b){M=b;try{var e=O(),d=N();return P.s(FS.lstat,e,d)}catch(g){return"undefined"!==typeof FS&&g instanceof FS.b||B(g),-g.c}},___syscall197:function(a,b){M=b;try{var e=P.i(),d=N();return P.s(FS.stat,e.path,d)}catch(g){return"undefined"!==typeof FS&&g instanceof FS.b||B(g),-g.c}},
___syscall219:function(a,b){M=b;return 0},___syscall220:function(a,b){M=b;try{var e=P.i(),d=N(),g=N();e.j||(e.j=FS.readdir(e.path));for(a=0;0<e.j.length&&a+268<=g;){var h=e.j.pop();if("."===h[0]){var k=1;var m=4}else{var r=FS.O(e.node,h);k=r.id;m=FS.K(r.mode)?2:FS.L(r.mode)?4:FS.M(r.mode)?10:8}z[d+a>>2]=k;z[d+a+4>>2]=e.position;ta[d+a+8>>1]=268;D[d+a+10>>0]=m;na(h,E,d+a+11,256);a+=268}return a}catch(t){return"undefined"!==typeof FS&&t instanceof FS.b||B(t),-t.c}},___syscall221:function(a,b){M=b;return 0},
___syscall3:function(a,b){M=b;try{var e=P.i(),d=N(),g=N();return FS.read(e,D,d,g)}catch(h){return"undefined"!==typeof FS&&h instanceof FS.b||B(h),-h.c}},___syscall33:function(a,b){M=b;try{var e=O(),d=N();return P.H(e,d)}catch(g){return"undefined"!==typeof FS&&g instanceof FS.b||B(g),-g.c}},___syscall38:function(a,b){M=b;try{var e=O(),d=O();FS.rename(e,d);return 0}catch(g){return"undefined"!==typeof FS&&g instanceof FS.b||B(g),-g.c}},___syscall4:function(a,b){M=b;try{var e=P.i(),d=N(),g=N();return FS.write(e,
D,d,g)}catch(h){return"undefined"!==typeof FS&&h instanceof FS.b||B(h),-h.c}},___syscall40:function(a,b){M=b;try{var e=O();FS.rmdir(e);return 0}catch(d){return"undefined"!==typeof FS&&d instanceof FS.b||B(d),-d.c}},___syscall5:function(a,b){M=b;try{var e=O(),d=N(),g=N();return FS.open(e,d,g).fd}catch(h){return"undefined"!==typeof FS&&h instanceof FS.b||B(h),-h.c}},___syscall54:function(a,b){M=b;return 0},___syscall6:function(a,b){M=b;try{var e=P.i();FS.close(e);return 0}catch(d){return"undefined"!==
typeof FS&&d instanceof FS.b||B(d),-d.c}},___unlock:function(){},_abort:function(){c.abort()},_clock:R,_clock_gettime:function(a,b){if(0===a)a=Date.now();else if(1===a&&(q||"undefined"!==typeof dateNow||(n||p)&&self.performance&&self.performance.now))a=S();else return Ma(22),-1;z[b>>2]=a/1E3|0;z[b+4>>2]=a%1E3*1E6|0;return 0},_emscripten_memcpy_big:function(a,b,e){E.set(E.subarray(b,b+e),a);return a},_exit:function(a){c.exit(a)},_fabs:Ja,_getenv:U,_gettimeofday:function(a){var b=Date.now();z[a>>2]=
b/1E3|0;z[a+4>>2]=b%1E3*1E3|0;return 0},_gmtime_r:function(a,b){a=new Date(1E3*z[a>>2]);z[b>>2]=a.getUTCSeconds();z[b+4>>2]=a.getUTCMinutes();z[b+8>>2]=a.getUTCHours();z[b+12>>2]=a.getUTCDate();z[b+16>>2]=a.getUTCMonth();z[b+20>>2]=a.getUTCFullYear()-1900;z[b+24>>2]=a.getUTCDay();z[b+36>>2]=0;z[b+32>>2]=0;z[b+28>>2]=(a.getTime()-Date.UTC(a.getUTCFullYear(),0,1,0,0,0,0))/864E5|0;z[b+40>>2]=Sa;return b},_llvm_exp2_f32:Ta,_llvm_exp2_f64:function(){return Ta.apply(null,arguments)},_llvm_trunc_f64:Ka,
_localtime_r:function(a,b){Wa();a=new Date(1E3*z[a>>2]);z[b>>2]=a.getSeconds();z[b+4>>2]=a.getMinutes();z[b+8>>2]=a.getHours();z[b+12>>2]=a.getDate();z[b+16>>2]=a.getMonth();z[b+20>>2]=a.getFullYear()-1900;z[b+24>>2]=a.getDay();var e=new Date(a.getFullYear(),0,1);z[b+28>>2]=(a.getTime()-e.getTime())/864E5|0;z[b+36>>2]=-(60*a.getTimezoneOffset());var d=(new Date(2E3,6,1)).getTimezoneOffset();e=e.getTimezoneOffset();a=(d!=e&&a.getTimezoneOffset()==Math.min(e,d))|0;z[b+32>>2]=a;z[b+40>>2]=z[W+(a?4:0)>>
2];return b},_mktime:function(a){Wa();var b=new Date(z[a+20>>2]+1900,z[a+16>>2],z[a+12>>2],z[a+8>>2],z[a+4>>2],z[a>>2],0),e=z[a+32>>2],d=b.getTimezoneOffset(),g=new Date(b.getFullYear(),0,1),h=(new Date(2E3,6,1)).getTimezoneOffset(),k=g.getTimezoneOffset(),m=Math.min(k,h);0>e?z[a+32>>2]=Number(h!=k&&m==d):0<e!=(m==d)&&(h=Math.max(k,h),b.setTime(b.getTime()+6E4*((0<e?m:h)-d)));z[a+24>>2]=b.getDay();z[a+28>>2]=(b.getTime()-g.getTime())/864E5|0;return b.getTime()/1E3|0},_nanosleep:function(a,b){var e=
z[a>>2];a=z[a+4>>2];0!==b&&(z[b>>2]=0,z[b+4>>2]=0);b=(1E6*e+a/1E3)/1E3;if((n||p)&&self.performance&&self.performance.now)for(e=self.performance.now();self.performance.now()-e<b;);else for(e=Date.now();Date.now()-e<b;);return 0},_strftime:function(a,b,e,d){function g(a,b,d){for(a="number"===typeof a?a.toString():a||"";a.length<b;)a=d[0]+a;return a}function h(a,b){return g(a,b,"0")}function k(a,b){function d(a){return 0>a?-1:0<a?1:0}var e;0===(e=d(a.getFullYear()-b.getFullYear()))&&0===(e=d(a.getMonth()-
b.getMonth()))&&(e=d(a.getDate()-b.getDate()));return e}function m(a){switch(a.getDay()){case 0:return new Date(a.getFullYear()-1,11,29);case 1:return a;case 2:return new Date(a.getFullYear(),0,3);case 3:return new Date(a.getFullYear(),0,2);case 4:return new Date(a.getFullYear(),0,1);case 5:return new Date(a.getFullYear()-1,11,31);case 6:return new Date(a.getFullYear()-1,11,30)}}function r(a){a=ab(new Date(a.a+1900,0,1),a.m);var b=m(new Date(a.getFullYear()+1,0,4));return 0>=k(m(new Date(a.getFullYear(),
0,4)),a)?0>=k(b,a)?a.getFullYear()+1:a.getFullYear():a.getFullYear()-1}var t=z[d+40>>2];d={D:z[d>>2],C:z[d+4>>2],l:z[d+8>>2],g:z[d+12>>2],f:z[d+16>>2],a:z[d+20>>2],u:z[d+24>>2],m:z[d+28>>2],P:z[d+32>>2],B:z[d+36>>2],F:t?F(t):""};e=F(e);t={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S","%x":"%m/%d/%y","%X":"%H:%M:%S"};for(var w in t)e=e.replace(new RegExp(w,"g"),t[w]);var Na="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),
Oa="January February March April May June July August September October November December".split(" ");t={"%a":function(a){return Na[a.u].substring(0,3)},"%A":function(a){return Na[a.u]},"%b":function(a){return Oa[a.f].substring(0,3)},"%B":function(a){return Oa[a.f]},"%C":function(a){return h((a.a+1900)/100|0,2)},"%d":function(a){return h(a.g,2)},"%e":function(a){return g(a.g,2," ")},"%g":function(a){return r(a).toString().substring(2)},"%G":function(a){return r(a)},"%H":function(a){return h(a.l,2)},
"%I":function(a){a=a.l;0==a?a=12:12<a&&(a-=12);return h(a,2)},"%j":function(a){return h(a.g+Ya(X(a.a+1900)?Za:$a,a.f-1),3)},"%m":function(a){return h(a.f+1,2)},"%M":function(a){return h(a.C,2)},"%n":function(){return"\n"},"%p":function(a){return 0<=a.l&&12>a.l?"AM":"PM"},"%S":function(a){return h(a.D,2)},"%t":function(){return"\t"},"%u":function(a){return(new Date(a.a+1900,a.f+1,a.g,0,0,0,0)).getDay()||7},"%U":function(a){var b=new Date(a.a+1900,0,1),d=0===b.getDay()?b:ab(b,7-b.getDay());a=new Date(a.a+
1900,a.f,a.g);return 0>k(d,a)?h(Math.ceil((31-d.getDate()+(Ya(X(a.getFullYear())?Za:$a,a.getMonth()-1)-31)+a.getDate())/7),2):0===k(d,b)?"01":"00"},"%V":function(a){var b=m(new Date(a.a+1900,0,4)),d=m(new Date(a.a+1901,0,4)),e=ab(new Date(a.a+1900,0,1),a.m);return 0>k(e,b)?"53":0>=k(d,e)?"01":h(Math.ceil((b.getFullYear()<a.a+1900?a.m+32-b.getDate():a.m+1-b.getDate())/7),2)},"%w":function(a){return(new Date(a.a+1900,a.f+1,a.g,0,0,0,0)).getDay()},"%W":function(a){var b=new Date(a.a,0,1),d=1===b.getDay()?
b:ab(b,0===b.getDay()?1:7-b.getDay()+1);a=new Date(a.a+1900,a.f,a.g);return 0>k(d,a)?h(Math.ceil((31-d.getDate()+(Ya(X(a.getFullYear())?Za:$a,a.getMonth()-1)-31)+a.getDate())/7),2):0===k(d,b)?"01":"00"},"%y":function(a){return(a.a+1900).toString().substring(2)},"%Y":function(a){return a.a+1900},"%z":function(a){a=a.B;var b=0<=a;a=Math.abs(a)/60;return(b?"+":"-")+String("0000"+(a/60*100+a%60)).slice(-4)},"%Z":function(a){return a.F},"%%":function(){return"%"}};for(w in t)0<=e.indexOf(w)&&(e=e.replace(new RegExp(w,
"g"),t[w](d)));w=V(e,!1);if(w.length>b)return 0;D.set(w,a);return w.length-1},DYNAMICTOP_PTR:y,STACKTOP:H};var kb=c.asm(c.v,c.w,buffer);c.asm=kb;c._add_frame=function(){return c.asm._add_frame.apply(null,arguments)};c._close_stream=function(){return c.asm._close_stream.apply(null,arguments)};var ya=c._emscripten_replace_memory=function(){return c.asm._emscripten_replace_memory.apply(null,arguments)},Ra=c._free=function(){return c.asm._free.apply(null,arguments)};
c._free_buffer=function(){return c.asm._free_buffer.apply(null,arguments)};c._get_buffer=function(){return c.asm._get_buffer.apply(null,arguments)};var ja=c._malloc=function(){return c.asm._malloc.apply(null,arguments)};c._open_audio=function(){return c.asm._open_audio.apply(null,arguments)};c._open_video=function(){return c.asm._open_video.apply(null,arguments)};c._write_audio_frame=function(){return c.asm._write_audio_frame.apply(null,arguments)};
c._write_header=function(){return c.asm._write_header.apply(null,arguments)};var ka=c.stackAlloc=function(){return c.asm.stackAlloc.apply(null,arguments)};c.dynCall_vi=function(){return c.asm.dynCall_vi.apply(null,arguments)};c.asm=kb;c.then=function(a){if(c.calledRun)a(c);else{var b=c.onRuntimeInitialized;c.onRuntimeInitialized=function(){b&&b();a(c)}}return c};function u(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}u.prototype=Error();
u.prototype.constructor=u;K=function lb(){c.calledRun||mb();c.calledRun||(K=lb)};
function mb(){function a(){if(!c.calledRun&&(c.calledRun=!0,!ia)){Ha||(Ha=!0,I(Da));I(Ea);if(c.onRuntimeInitialized)c.onRuntimeInitialized();if(c.postRun)for("function"==typeof c.postRun&&(c.postRun=[c.postRun]);c.postRun.length;){var a=c.postRun.shift();Ga.unshift(a)}I(Ga)}}if(!(0<J)){if(c.preRun)for("function"==typeof c.preRun&&(c.preRun=[c.preRun]);c.preRun.length;)Ia();I(Ca);0<J||c.calledRun||(c.setStatus?(c.setStatus("Running..."),setTimeout(function(){setTimeout(function(){c.setStatus("")},
1);a()},1)):a())}}c.run=mb;c.exit=function(a,b){if(!b||!c.noExitRuntime||0!==a){if(!c.noExitRuntime&&(ia=!0,H=void 0,I(Fa),c.onExit))c.onExit(a);q&&process.exit(a);c.quit(a,new u(a))}};function B(a){if(c.onAbort)c.onAbort(a);void 0!==a?(c.print(a),c.printErr(a),a=JSON.stringify(a)):a="";ia=!0;throw"abort("+a+"). Build with -s ASSERTIONS=1 for more info.";}c.abort=B;if(c.preInit)for("function"==typeof c.preInit&&(c.preInit=[c.preInit]);0<c.preInit.length;)c.preInit.pop()();c.noExitRuntime=!0;mb();


  return WasmVideoEncoderTest2;
};
if (typeof exports === 'object' && typeof module === 'object')
  module.exports = WasmVideoEncoderTest2;
else if (typeof define === 'function' && define['amd'])
  define([], function() { return WasmVideoEncoderTest2; });
else if (typeof exports === 'object')
  exports["WasmVideoEncoderTest2"] = WasmVideoEncoderTest2;
